\connect climbing_meetup

INSERT INTO states (name)
VALUES ('Alabama'), ('Alaska'),('Arizona'),('Arkansas'),('California'),('Colorado'),('Connecticut'),('Delaware'),('Florida'),
    ('Georgia'),('Hawaii'),('Idaho'),('Illinois'),('Indiana'),('Iowa'),('Kansas'),('Kentucky'),('Louisiana'),('Maine'),
    ('Maryland'),('Massachusetts'),('Michigan'),('Minnesota'),('Mississippi'),('Missouri'),('Montana'),('Nebraska'),('Nevada'),('New Hampshire'),
    ('New Jersey'),('New Mexico'),('New York'),('North Carolina'),('North Dakota'),('Ohio'),('Oklahoma'),('Oregon'),('Pennsylvania'),('Rhode Island'),
    ('South Carolina'),('South Dakota'),('Tennessee'),('Texas'),('Utah'),('Vermont'),('Virgnia'),('Washington'),('West Virgnia'),('Wisconsin'),('Wyoming');


INSERT INTO locations (name,state_id,type)
VALUES ($$Auburn University Recreation and Wellness Center$$, 1, 'Gym'),
    ($$Birmingham Boulders$$, 1, 'Gym'),
    ($$Campus Recreation Center$$, 1, 'Gym'),
    ($$Crux Climbing$$, 1, 'Gym'),
    ($$Faucett Brothers Activity Center$$, 1, 'Gym'),
    ($$First Avenue Rocks$$, 1, 'Gym'),
    ($$Fortenberry-Colton Fitness Center$$, 1, 'Gym'),
    ($$Gadrock$$, 1, 'Gym'),
    ($$High Point Climbing - Birmingham$$, 1, 'Gym'),
    ($$High Point Climbing - Huntsville$$, 1, 'Gym'),
    ($$University of Alabama$$, 1, 'Gym'),
    ($$University of South Alabama - Student Recreation Center$$, 1, 'Gym'),
    ($$YMCA Camp Cosby Alpine Tower$$, 1, 'Gym'),
    ($$Alaska Rock Gym$$, 2, 'Gym'),
    ($$Alaska-Pacific University Climbing Wall$$, 2, 'Gym'),
    ($$Ascension Rock Club$$, 2, 'Gym'),
    ($$Cassel Rock$$, 2, 'Gym'),
    ($$Denali Rock Climbing$$, 2, 'Gym'),
    ($$Piuraagvik Recreation Center$$, 2, 'Gym'),
    ($$Skagway Recreation Center$$, 2, 'Gym'),
    ($$The Alaska Club South$$, 2, 'Gym'),
    ($$The Alaska Club Valley$$, 2, 'Gym'),
    ($$The Alaska Club West$$, 2, 'Gym'),
    ($$The Rock Dump Indoor Climbing Gym$$, 2, 'Gym'),
    ($$University of Alaska Southeast Climbing Wall$$, 2, 'Gym'),
    ($$University of Alaska Student Rec Center$$, 2, 'Gym'),
    ($$Valdez Middle School Climbing Gym$$, 2, 'Gym'),
    ($$Alta Boulders$$, 3, 'Gym'),
    ($$Alta Climbing and Fitness$$, 3, 'Gym'),
    ($$Ape Index$$, 3, 'Gym'),
    ($$AZ on the Rocks$$, 3, 'Gym'),
    ($$Beta Bouldering Gym$$, 3, 'Gym'),
    ($$Black Rock Bouldering Gym$$, 3, 'Gym'),
    ($$Ciba Climbing$$, 3, 'Gym'),
    ($$Climbmax Climbing Gym$$, 3, 'Gym'),
    ($$Flagstaff Climbing: Downtown Crag$$, 3, 'Gym'),
    ($$Flagstaff Climbing: Main Street Boulders$$, 3, 'Gym'),
    ($$Focus Climbing Center$$, 3, 'Gym'),
    ($$GCU Climbing Wall$$, 3, 'Gym'),
    ($$Gecko Climbing Gym$$, 3, 'Gym'),
    ($$Gripstone$$, 3, 'Gym'),
    ($$Lifetime Fitness$$, 3, 'Gym'),
    ($$Lifetime Fitnesses Palm Valley$$, 3, 'Gym'),
    ($$Miraval Luxury Resort$$, 3, 'Gym'),
    ($$Northern Arizona University Climbing…$$, 3, 'Gym'),
    ($$Phoenix Rock Gym$$, 3, 'Gym'),
    ($$Prescott Rocks and Rec$$, 3, 'Gym'),
    ($$Rock Solid Climbing & Fitness$$, 3, 'Gym'),
    ($$Rocks and Ropes Climbing Gym$$, 3, 'Gym'),
    ($$The Bloc$$, 3, 'Gym'),
    ($$Climb Bentonville$$, 4, 'Gym'),
    ($$Elevate sports gym$$, 4, 'Gym'),
    ($$La Casa Pollo$$, 4, 'Gym'),
    ($$Little Rock Climbing Center$$, 4, 'Gym'),
    ($$Ozark Climbing Gym$$, 4, 'Gym'),
    ($$The Crag$$, 4, 'Gym'),
    ($$The Wall (Russellville Climbing Center)$$, 4, 'Gym'),
    ($$University of Arkansas Outdoor Center$$, 4, 'Gym'),
    ($$Vertical Horizons$$, 4, 'Gym'),
    ($$Zion Climbing Center$$, 4, 'Gym'),
    ($$Frog's Athletic Club$$, 5, 'Gym'),
    ($$24 Hour Fitness - Lakeshore Towers$$, 5, 'Gym'),
    ($$Adventure Associates$$, 5, 'Gym'),
    ($$Aesthetic Climbing Gym$$, 5, 'Gym'),
    ($$Agoura Hills/Calabasas Community Center$$, 5, 'Gym'),
    ($$Alpine$$, 5, 'Gym'),
    ($$Aztec Recreation Center$$, 5, 'Gym'),
    ($$Benchmark Climbing - San Francisco$$, 5, 'Gym'),
    ($$Benchmark Climbing - Berkley$$, 5, 'Gym'),
    ($$Bladium Rock Wall$$, 5, 'Gym'),
    ($$Blue Granite Climbing Gym$$, 5, 'Gym'),
    ($$Boulderdash Indoor Rock Climbing$$, 5, 'Gym'),
    ($$Boulderdash SFV$$, 5, 'Gym'),
    ($$Boulderdash Ventura$$, 5, 'Gym'),
    ($$Bridges Rock Gym$$, 5, 'Gym'),
    ($$Cal Poly Pomona, Bronco Recreation and Intramural Complex (BRIC)$$, 5, 'Gym'),
    ($$Class 5 Fitness$$, 5, 'Gym'),
    ($$Cliffs of Id$$, 5, 'Gym'),
    ($$Crux Climbing Center$$, 5, 'Gym'),
    ($$CSU San Bernardino$$, 5, 'Gym'),
    ($$Diablo Rock Gym$$, 5, 'Gym'),
    ($$Dogpatch Boulders$$, 5, 'Gym'),
    ($$Far North Climbing Gym$$, 5, 'Gym'),
    ($$Flowstone Climbing$$, 5, 'Gym'),
    ($$Gold Crush Climbing Gym$$, 5, 'Gym'),
    ($$Goleta Valley Athletic Club$$, 5, 'Gym'),
    ($$Granite Arch Climbing Center$$, 5, 'Gym'),
    ($$Gravity Works / Sports Exchange$$, 5, 'Gym'),
    ($$Great Western Power Co.$$, 5, 'Gym'),
    ($$Gritstone Rock Club$$, 5, 'Gym'),
    ($$Grotto Climbing & Yoga - Alvarado Canyon Rd.$$, 5, 'Gym'),
    ($$Grotto Climbing & Yoga - Miramar Rd.$$, 5, 'Gym'),
    ($$Gymnastics World$$, 5, 'Gym'),
    ($$Hangar 18 East Riverside$$, 5, 'Gym'),
    ($$Hangar 18 High Desert$$, 5, 'Gym'),
    ($$Hangar 18 Long Beach$$, 5, 'Gym'),
    ($$Hangar 18 Mission Viejo$$, 5, 'Gym'),
    ($$Hangar 18 Orange$$, 5, 'Gym'),
    ($$Hangar 18 Rancho Cucamonga$$, 5, 'Gym'),
    ($$Hangar 18 Riverside$$, 5, 'Gym'),
    ($$Hangar 18 San Clemente$$, 5, 'Gym'),
    ($$Hangar 18 Southbay$$, 5, 'Gym'),
    ($$Hangar 18 Upland$$, 5, 'Gym'),
    ($$Hanger 18 Arcadia$$, 5, 'Gym'),
    ($$High Altitude Fitness, Truckee, CA$$, 5, 'Gym'),
    ($$Hollywood Boulders$$, 5, 'Gym'),
    ($$Humboldt State University Student Recreation Center$$, 5, 'Gym'),
    ($$Ironworks$$, 5, 'Gym'),
    ($$Kids Party Central$$, 5, 'Gym'),
    ($$LA Boulders$$, 5, 'Gym'),
    ($$Long Beach Rising$$, 5, 'Gym'),
    ($$Mesa Rim - Climbing Academy$$, 5, 'Gym'),
    ($$Mesa Rim - Mira Mesa$$, 5, 'Gym'),
    ($$Mesa Rim - Mission Valley$$, 5, 'Gym'),
    ($$Mesa Rim - North City$$, 5, 'Gym'),
    ($$Metal Mark$$, 5, 'Gym'),
    ($$Mission Cliffs$$, 5, 'Gym'),
    ($$Movement Santa Clara$$, 5, 'Gym'),
    ($$North of the River$$, 5, 'Gym'),
    ($$Outback Climbing wall$$, 5, 'Gym'),
    ($$Pacific Edge Climbing$$, 5, 'Gym'),
    ($$Pacific Pipe$$, 5, 'Gym'),
    ($$Planet Granite - Belmont$$, 5, 'Gym'),
    ($$Planet Granite - San Francisco$$, 5, 'Gym'),
    ($$Planet Granite - Sunnyvale$$, 5, 'Gym'),
    ($$Rock Fitness$$, 5, 'Gym'),
    ($$Rocknasium$$, 5, 'Gym'),
    ($$Rockreation - Costa Mesa$$, 5, 'Gym'),
    ($$Rockreation - Los Angeles$$, 5, 'Gym'),
    ($$Rocktopia$$, 5, 'Gym'),
    ($$Rockzilla$$, 5, 'Gym'),
    ($$Sacramento Pipeworks$$, 5, 'Gym'),
    ($$Sage to Summit$$, 5, 'Gym'),
    ($$Sancturary Climbing & Fitness$$, 5, 'Gym'),
    ($$Santa Barbara Rock Gym$$, 5, 'Gym'),
    ($$Sender One Climbing - LAX$$, 5, 'Gym'),
    ($$Sender One Climbing - SNA$$, 5, 'Gym'),
    ($$Session Climbing$$, 5, 'Gym'),
    ($$Shasta Basecamp$$, 5, 'Gym'),
    ($$Shasta Rock Club$$, 5, 'Gym'),
    ($$SRC Rock Wall$$, 5, 'Gym'),
    ($$Student Recreation Center at CSUB$$, 5, 'Gym'),
    ($$Team Touchstone Training Facility$$, 5, 'Gym'),
    ($$Terrain Park Climbing Center$$, 5, 'Gym'),
    ($$The Boulder Field$$, 5, 'Gym'),
    ($$The Gravity Vault - Marin$$, 5, 'Gym'),
    ($$The Pad$$, 5, 'Gym'),
    ($$The Peak of Fremont$$, 5, 'Gym'),
    ($$The Pit$$, 5, 'Gym'),
    ($$The Post Climbing$$, 5, 'Gym'),
    ($$The Rock Gym$$, 5, 'Gym'),
    ($$The Stronghold Climbing Gym$$, 5, 'Gym'),
    ($$The Studio$$, 5, 'Gym'),
    ($$The Wall$$, 5, 'Gym'),
    ($$The Well at Sacramento State$$, 5, 'Gym'),
    ($$Top Out Climbing Gym$$, 5, 'Gym'),
    ($$Torrance South Bay YMCA$$, 5, 'Gym'),
    ($$Touchstone MetalMark$$, 5, 'Gym'),
    ($$TruHold Climbing$$, 5, 'Gym'),
    ($$Twisters Sports$$, 5, 'Gym'),
    ($$UCSB$$, 5, 'Gym'),
    ($$University of California - Irvine$$, 5, 'Gym'),
    ($$Verdigo Boulders$$, 5, 'Gym'),
    ($$Vert Rock Gym$$, 5, 'Gym'),
    ($$Vertex Climbing Center$$, 5, 'Gym'),
    ($$Vertical Hold - San Diego$$, 5, 'Gym'),
    ($$Vertical Hold - San Marcos$$, 5, 'Gym'),
    ($$Vertical Hold Gym$$, 5, 'Gym'),
    ($$Vertical Hold Sport Climbing Inc.$$, 5, 'Gym'),
    ($$Vital Climbing Gym - Carlsbad$$, 5, 'Gym'),
    ($$VITAL Climbing Gym - Murrieta$$, 5, 'Gym'),
    ($$Vital Oceanside$$, 5, 'Gym'),
    ($$WREC Climbing Gym$$, 5, 'Gym'),
    ($$ROCK'n & JAM'n 1$$, 6, 'Gym'),
    ($$ROCK'n & JAM'n2$$, 6, 'Gym'),
    ($$Adams State University Climbing Wall$$, 6, 'Gym'),
    ($$Adventure Unlimited Rock Gym$$, 6, 'Gym'),
    ($$Airborne Gymnastics$$, 6, 'Gym'),
    ($$Apex Center$$, 6, 'Gym'),
    ($$Ascent Studio$$, 6, 'Gym'),
    ($$Aspen Recreation Department Red Brick Climbing Gym$$, 6, 'Gym'),
    ($$Basecamp Bouldering$$, 6, 'Gym'),
    ($$Bass Pro Shops$$, 6, 'Gym'),
    ($$Boulder Rec Center - East$$, 6, 'Gym'),
    ($$Boulder Rock Club and Colorado Mountain School$$, 6, 'Gym'),
    ($$Bouldering wall at Spring Valley Center$$, 6, 'Gym'),
    ($$Broomfield Recreation Center Climbing Wall$$, 6, 'Gym'),
    ($$Buchanan Park Recreation Center$$, 6, 'Gym'),
    ($$Carla Madison Recreation Center$$, 6, 'Gym'),
    ($$Charles Whitlock Climbing Gym$$, 6, 'Gym'),
    ($$CityRock Colorado Springs$$, 6, 'Gym'),
    ($$CMU Student Recreation Center$$, 6, 'Gym'),
    ($$Colorado Athletic Training School$$, 6, 'Gym'),
    ($$CSU Pueblo Climbing Wall$$, 6, 'Gym'),
    ($$CSU Rec Center$$, 6, 'Gym'),
    ($$Denver Bouldering Club$$, 6, 'Gym'),
    ($$Denver Bouldering Club South$$, 6, 'Gym'),
    ($$Durango Rec center$$, 6, 'Gym'),
    ($$Eagle Climbing + Fitness$$, 6, 'Gym'),
    ($$Eastridge Recreation Center$$, 6, 'Gym'),
    ($$Epic Climbing Gym$$, 6, 'Gym'),
    ($$Erie Community Center$$, 6, 'Gym'),
    ($$Estes Park Mountain Shop$$, 6, 'Gym'),
    ($$Ft. Lewis College$$, 6, 'Gym'),
    ($$G1 Climbing + Fitness$$, 6, 'Gym'),
    ($$Glenwood Springs Rec Center$$, 6, 'Gym'),
    ($$Golden Community Center$$, 6, 'Gym'),
    ($$Grand Park Community Recreation Center$$, 6, 'Gym'),
    ($$Grand Valley Climbing$$, 6, 'Gym'),
    ($$Gravity Lab$$, 6, 'Gym'),
    ($$Greeley Downtown Rec Center$$, 6, 'Gym'),
    ($$Grip Bouldering$$, 6, 'Gym'),
    ($$Gripstone Climbing and Fitness$$, 6, 'Gym'),
    ($$Gunnison Community Center$$, 6, 'Gym'),
    ($$Gypsum Rec Center Climbing Pinnacle$$, 6, 'Gym'),
    ($$Lakeshore Athletic Club$$, 6, 'Gym'),
    ($$Lakewood Climbing Wall$$, 6, 'Gym'),
    ($$LCA Climbing Center$$, 6, 'Gym'),
    ($$Lifetime Fitness$$, 6, 'Gym'),
    ($$Longmont Climbing Collective$$, 6, 'Gym'),
    ($$Longmont Recreation Center$$, 6, 'Gym'),
    ($$Miramont North$$, 6, 'Gym'),
    ($$Monkey House Carbondale$$, 6, 'Gym'),
    ($$Movement Baker$$, 6, 'Gym'),
    ($$Movement Boulder$$, 6, 'Gym'),
    ($$Movement Englewood$$, 6, 'Gym'),
    ($$Movement Golden$$, 6, 'Gym'),
    ($$Movement Rino$$, 6, 'Gym'),
    ($$Parker Fieldhouse (The Pinnacle)$$, 6, 'Gym'),
    ($$Peak Fitness$$, 6, 'Gym'),
    ($$Pure Bouldering$$, 6, 'Gym'),
    ($$REI - Denver$$, 6, 'Gym'),
    ($$REI - Englewood$$, 6, 'Gym'),
    ($$REI - Lakewood$$, 6, 'Gym'),
    ($$Ridgway Secondary School Climbing Wall$$, 6, 'Gym'),
    ($$Springs Climbing Center$$, 6, 'Gym'),
    ($$Summit Climbing Gym$$, 6, 'Gym'),
    ($$The Gym of the Rockies$$, 6, 'Gym'),
    ($$The Point Athletic$$, 6, 'Gym'),
    ($$The Ridge Recreation Center$$, 6, 'Gym'),
    ($$The Rock Lounge$$, 6, 'Gym'),
    ($$The Spot - Boulder$$, 6, 'Gym'),
    ($$The Spot - Denver$$, 6, 'Gym'),
    ($$The Spot Golden$$, 6, 'Gym'),
    ($$The Spot Louisville$$, 6, 'Gym'),
    ($$Town of Breckenridge Climbing Wall$$, 6, 'Gym'),
    ($$Trails Recreation Center$$, 6, 'Gym'),
    ($$Übergrippen Indoor Climbing Crag - Denver$$, 6, 'Gym'),
    ($$Übergrippen Indoor Climbing Crag - Castle Rock$$, 6, 'Gym'),
    ($$UNC Campus Recreation Center$$, 6, 'Gym'),
    ($$University of Colorado Climbing Gym$$, 6, 'Gym'),
    ($$Vail Mountain Athletic Club$$, 6, 'Gym'),
    ($$WECMRD Field House at Edwards$$, 6, 'Gym'),
    ($$Western Colorado University$$, 6, 'Gym'),
    ($$Westminster Climbing Wall$$, 6, 'Gym'),
    ($$Wheat Ridge Recreation Center$$, 6, 'Gym'),
    ($$Whetstone$$, 6, 'Gym'),
    ($$Wooden Mountain$$, 6, 'Gym'),
    ($$YMCA - Pueblo$$, 6, 'Gym'),
    ($$Beta Climbing$$, 7, 'Gym'),
    ($$Central Rock Gym (Glastonbury)$$, 7, 'Gym'),
    ($$Central Rock Gym - West Hartford$$, 7, 'Gym'),
    ($$City Climb Gym$$, 7, 'Gym'),
    ($$Climb Danbury$$, 7, 'Gym'),
    ($$Easton Community Center - MT. ECC Indoor Climbing Wall$$, 7, 'Gym'),
    ($$Prime Climb$$, 7, 'Gym'),
    ($$Rock Climb Fairfield$$, 7, 'Gym'),
    ($$Sono Field House$$, 7, 'Gym'),
    ($$Stone Age Rock Gym$$, 7, 'Gym'),
    ($$The CT Rock Gym$$, 7, 'Gym'),
    ($$Jewish Community Center Climbing Wall$$, 8, 'Gym'),
    ($$RISE Fitness + Adventure$$, 8, 'Gym'),
    ($$The Delaware Rock Gym$$, 8, 'Gym'),
    ($$University of Delaware Climbing Wall$$, 8, 'Gym'),
    ($$Weatherford's Climbing Wall$$, 9, 'Gym'),
    ($$Adventure HQ$$, 9, 'Gym'),
    ($$Aiguille Rock Climbing Center$$, 9, 'Gym'),
    ($$Alchemy Climbing$$, 9, 'Gym'),
    ($$Beaches Rock Gym$$, 9, 'Gym'),
    ($$Blue Swan Boulders$$, 9, 'Gym'),
    ($$Boca Prep International School$$, 9, 'Gym'),
    ($$Broward College South Campus$$, 9, 'Gym'),
    ($$Central Rock Gym - Tampa$$, 9, 'Gym'),
    ($$Coral Cliffs indoor rock climbing wall$$, 9, 'Gym'),
    ($$Cornerstone Rock Gym$$, 9, 'Gym'),
    ($$Daytona Lagoon$$, 9, 'Gym'),
    ($$DynoClimb$$, 9, 'Gym'),
    ($$Fort Rock Climbing Center$$, 9, 'Gym'),
    ($$On The Edge Rock Climbing Gym$$, 9, 'Gym'),
    ($$Project Rock$$, 9, 'Gym'),
    ($$Rec Rock$$, 9, 'Gym'),
    ($$Rock Out Climbing Gym$$, 9, 'Gym'),
    ($$Rox Climbing Gym$$, 9, 'Gym'),
    ($$Sheinberg Family YMCA of Weston$$, 9, 'Gym'),
    ($$Stone Climbing$$, 9, 'Gym'),
    ($$Sun Country Rocks$$, 9, 'Gym'),
    ($$Tallahassee Rock Gym$$, 9, 'Gym'),
    ($$The Edge Rock Climbing Gym$$, 9, 'Gym'),
    ($$The Edge Rock Gym$$, 9, 'Gym'),
    ($$The Knot$$, 9, 'Gym'),
    ($$UCF Recreational Center Rock Tower$$, 9, 'Gym'),
    ($$University Climbing Wall$$, 9, 'Gym'),
    ($$UWF Climbing Center$$, 9, 'Gym'),
    ($$Vertical Ventures: St. Pete$$, 9, 'Gym'),
    ($$Active Climbing - Athens$$, 10, 'Gym'),
    ($$Active Climbing - Grovetown$$, 10, 'Gym'),
    ($$Adrenaline Climbing$$, 10, 'Gym'),
    ($$Andretti Indoor Karting & Games$$, 10, 'Gym'),
    ($$Camp Coleman Climbing Wall$$, 10, 'Gym'),
    ($$Centennial Place YMCA$$, 10, 'Gym'),
    ($$Corkan Family Recreation Exteme Climbing Room$$, 10, 'Gym'),
    ($$Ed Isakson YMCA$$, 10, 'Gym'),
    ($$Escalade Rock Climbing Gym$$, 10, 'Gym'),
    ($$Escalade Rock Climbing PTC$$, 10, 'Gym'),
    ($$Georgia Southern University Climbing Wall$$, 10, 'Gym'),
    ($$Lifetime Fitness Climbing Gym$$, 10, 'Gym'),
    ($$Macon Rocks Climbing Gym$$, 10, 'Gym'),
    ($$Middle Georgia College Wellness Center$$, 10, 'Gym'),
    ($$Midtown Athletic Club at Windy Hill$$, 10, 'Gym'),
    ($$Outdoor Recreation at Georgia Tech - Climbing Wall$$, 10, 'Gym'),
    ($$Savannah Climbing CoOp$$, 10, 'Gym'),
    ($$Smith Fitness Center$$, 10, 'Gym'),
    ($$Stone Summit Atlanta$$, 10, 'Gym'),
    ($$Stone Summit Kennesaw$$, 10, 'Gym'),
    ($$Stone Summit Midtown$$, 10, 'Gym'),
    ($$The Climb& 8217 n Shop$$, 10, 'Gym'),
    ($$The Overlook Boulder + Fitness$$, 10, 'Gym'),
    ($$Treadstone Columbus$$, 10, 'Gym'),
    ($$University of Georgia Climbing Wall$$, 10, 'Gym'),
    ($$University of West Georgia Climbing Wall$$, 10, 'Gym'),
    ($$Valdosta State University$$, 10, 'Gym'),
    ($$Wall Crawler Rock Club$$, 10, 'Gym'),
    ($$Big Island Climbing$$, 11, 'Gym'),
    ($$HiClimb$$, 11, 'Gym'),
    ($$Oahu Bouldering Gym$$, 11, 'Gym'),
    ($$Volcanic Rock Gym$$, 11, 'Gym'),
    ($$Asana Climbing Gym$$, 12, 'Gym'),
    ($$Boise Rock Gym$$, 12, 'Gym'),
    ($$Boise State University Rock Climbing Wall$$, 12, 'Gym'),
    ($$Caldwell Family YMCA$$, 12, 'Gym'),
    ($$Downtown YMCA$$, 12, 'Gym'),
    ($$Gemstone Climbing Center$$, 12, 'Gym'),
    ($$Idaho State University Climbing Wall$$, 12, 'Gym'),
    ($$Kroc Center Climbing Wall$$, 12, 'Gym'),
    ($$North Idaho College Climbing Wall$$, 12, 'Gym'),
    ($$Regional Rock Walls$$, 12, 'Gym'),
    ($$Sandpoint Rock Gym$$, 12, 'Gym'),
    ($$Sticks and Stones$$, 12, 'Gym'),
    ($$Stonewalls Rock Gym$$, 12, 'Gym'),
    ($$Teton Rock Gym$$, 12, 'Gym'),
    ($$The Commons Climbing Gym$$, 12, 'Gym'),
    ($$The Edge Climbing and Fitness$$, 12, 'Gym'),
    ($$University of Idaho Climbing Wall$$, 12, 'Gym'),
    ($$vertical View$$, 12, 'Gym'),
    ($$West Family YMCA$$, 12, 'Gym'),
    ($$Wood River YMCA$$, 12, 'Gym'),
    ($$O'Fallon YMCA Climbing Wall$$, 13, 'Gym'),
    ($$Annerino Center wall$$, 13, 'Gym'),
    ($$B.R.Ryall YMCA$$, 13, 'Gym'),
    ($$Broadway Armory$$, 13, 'Gym'),
    ($$Brooklyn Boulders Chicago$$, 13, 'Gym'),
    ($$Cahokia Area YMCA Climbing Wall$$, 13, 'Gym'),
    ($$Climb On$$, 13, 'Gym'),
    ($$Climbing Wall$$, 13, 'Gym'),
    ($$Climbing Wall and Roof$$, 13, 'Gym'),
    ($$Decatur Indoor Sports Center (DISC)$$, 13, 'Gym'),
    ($$Downtown Belleville YMCA climbing wall$$, 13, 'Gym'),
    ($$Evanston Athletic Club$$, 13, 'Gym'),
    ($$First Ascent - Arlington Heights$$, 13, 'Gym'),
    ($$First Ascent - Block 37$$, 13, 'Gym'),
    ($$First Ascent - Humboldt Park$$, 13, 'Gym'),
    ($$First Ascent - Peoria$$, 13, 'Gym'),
    ($$First Ascent - Uptown$$, 13, 'Gym'),
    ($$First Ascent Avondale$$, 13, 'Gym'),
    ($$Gurnee Park District, Hunt Club Park…$$, 13, 'Gym'),
    ($$Hidden Peak Climbing Gym$$, 13, 'Gym'),
    ($$Lakeshore Athletic Club-Illinois Center$$, 13, 'Gym'),
    ($$Latof YMCA - Adventure Center$$, 13, 'Gym'),
    ($$Libertyville Sports Complex$$, 13, 'Gym'),
    ($$Life Time Climb$$, 13, 'Gym'),
    ($$Lifetime Fitness - Niles$$, 13, 'Gym'),
    ($$Lifetime Fitness - Du Page$$, 13, 'Gym'),
    ($$Lifetime Fitness - Bloomingdale$$, 13, 'Gym'),
    ($$Lifetime Fitness Climbing Wall - Algonquin$$, 13, 'Gym'),
    ($$Lifetime Fitness Climbing Wall - Orland$$, 13, 'Gym'),
    ($$Lifetime Fitness Climbing Wall - Schaumburg$$, 13, 'Gym'),
    ($$Lifetime Fitness Climbing Wall - Lyons$$, 13, 'Gym'),
    ($$Lincoln Park Athletic Club$$, 13, 'Gym'),
    ($$Metro Sports$$, 13, 'Gym'),
    ($$Movement Lincoln Park$$, 13, 'Gym'),
    ($$Movement Wrigleyville$$, 13, 'Gym'),
    ($$North Wall$$, 13, 'Gym'),
    ($$Oak Park Formula Fitness Club$$, 13, 'Gym'),
    ($$Off Belay Rock Club$$, 13, 'Gym'),
    ($$Old Town Indoor Rock Climbing$$, 13, 'Gym'),
    ($$Outdoor Center - YMCA of Southwest Illinois$$, 13, 'Gym'),
    ($$Rockaway Climbing wall$$, 13, 'Gym'),
    ($$South Suburban Cheer and Tumbling$$, 13, 'Gym'),
    ($$Southern Illinois University Edwardsville Climbing Wall$$, 13, 'Gym'),
    ($$Sportsplex$$, 13, 'Gym'),
    ($$Springfield Racquet & Fitness Center$$, 13, 'Gym'),
    ($$The Centre of Elgin$$, 13, 'Gym'),
    ($$The Proving Ground Bouldering Gym$$, 13, 'Gym'),
    ($$University of Illinois Activities & Recreation Center$$, 13, 'Gym'),
    ($$University of Illinois at Chicago Climbing Wall$$, 13, 'Gym'),
    ($$Upper Limits Inc.$$, 13, 'Gym'),
    ($$Urbana Boulders$$, 13, 'Gym'),
    ($$Vertical Endeavors - Glendale Heights$$, 13, 'Gym'),
    ($$Xsport Fitness - W. North Ave.$$, 13, 'Gym'),
    ($$XSport Fitness - South State St.$$, 13, 'Gym'),
    ($$YMCA of Rock River Valley$$, 13, 'Gym'),
    ($$Jackson Falls 541$$, 13, 'Outdoor'),
    ($$The Holy Boulders 231$$, 13, 'Outdoor'),
    ($$Ball State University Indoor Climbing Wall$$, 14, 'Gym'),
    ($$Climb Lafayette$$, 14, 'Gym'),
    ($$Climb Time Indy$$, 14, 'Gym'),
    ($$Columbus Rock Gym$$, 14, 'Gym'),
    ($$Earth Adventures Unlimited$$, 14, 'Gym'),
    ($$EPIC Climbing and Fitness$$, 14, 'Gym'),
    ($$France A. Córdova Recreational Sports Center$$, 14, 'Gym'),
    ($$Goshen College Rec Center$$, 14, 'Gym'),
    ($$Hoosier Heights$$, 14, 'Gym'),
    ($$Hoosier Heights (Indianapolis)$$, 14, 'Gym'),
    ($$Indiana University Outdoor Adventures$$, 14, 'Gym'),
    ($$Kosciusko Community YMCA$$, 14, 'Gym'),
    ($$Kroc Corps Community Center South Bend$$, 14, 'Gym'),
    ($$Lifetime Fitness Climbing Wall$$, 14, 'Gym'),
    ($$North Mass Boulder$$, 14, 'Gym'),
    ($$University of Notre Dame Climbing Gym$$, 14, 'Gym'),
    ($$Vertical Challenge$$, 14, 'Gym'),
    ($$Vertical eXcape$$, 14, 'Gym'),
    ($$Climb Iowa$$, 15, 'Gym'),
    ($$Climb Iowa East Village$$, 15, 'Gym'),
    ($$Iowa State - Lied Rec Center$$, 15, 'Gym'),
    ($$Long Lines Family Recreation Center$$, 15, 'Gym'),
    ($$Luther College Climbing Wall$$, 15, 'Gym'),
    ($$Maharishi International University$$, 15, 'Gym'),
    ($$SportsPlex West$$, 15, 'Gym'),
    ($$State Gym-Iowa State University$$, 15, 'Gym'),
    ($$The Grotto @ Coe College$$, 15, 'Gym'),
    ($$The W at Wartburg College$$, 15, 'Gym'),
    ($$University of Iowa$$, 15, 'Gym'),
    ($$University of Northern Iowa Wellness and Recreation Center$$, 15, 'Gym'),
    ($$Andover YMCA$$, 16, 'Gym'),
    ($$Bliss Climbing and Fitness$$, 16, 'Gym'),
    ($$Climb Lawrence$$, 16, 'Gym'),
    ($$Dynamic Earth Equipment$$, 16, 'Gym'),
    ($$Emerald City Gymnastics climbing wall$$, 16, 'Gym'),
    ($$Genesis Health Club$$, 16, 'Gym'),
    ($$Kansas Cliff Club$$, 16, 'Gym'),
    ($$KU Rock$$, 16, 'Gym'),
    ($$Life Time Fitness - Lawrence$$, 16, 'Gym'),
    ($$Lifetime Fitness - Overland Park$$, 16, 'Gym'),
    ($$North YMCA$$, 16, 'Gym'),
    ($$Northwest YMCA$$, 16, 'Gym'),
    ($$Rec Center - Kansas State University$$, 16, 'Gym'),
    ($$RoKC Olathe$$, 16, 'Gym'),
    ($$Washburn University Student Recreation and Wellness Center$$, 16, 'Gym'),
    ($$White elephant buttress$$, 16, 'Gym'),
    ($$Hester's Family Fitness$$, 17, 'Gym'),
    ($$Asbury University Climbing Gym$$, 17, 'Gym'),
    ($$ClimbNulu$$, 17, 'Gym'),
    ($$CLYM$$, 17, 'Gym'),
    ($$Eastern Kentucky University Climbing Wall$$, 17, 'Gym'),
    ($$Johnson Center at UK$$, 17, 'Gym'),
    ($$LEF$$, 17, 'Gym'),
    ($$Northern Kentucky University Bouldering Wall$$, 17, 'Gym'),
    ($$Rock Gem$$, 17, 'Gym'),
    ($$Rocksport Inc.$$, 17, 'Gym'),
    ($$Vertical Excape Bowling Green$$, 17, 'Gym'),
    ($$Carter Caves$$, 17, 'Outdoor'),
    ($$Cherokee Park$$, 17, 'Outdoor'),
    ($$Chicken Head Rock$$, 17, 'Outdoor'),
    ($$Foxtown Boulders$$, 17, 'Outdoor'),
    ($$Knobs Forest Knobs$$, 17, 'Outdoor'),
    ($$Lockegee$$, 17, 'Outdoor'),
    ($$Murder Branch$$, 17, 'Outdoor'),
    ($$Otter Creek$$, 17, 'Outdoor'),
    ($$Purple Bridge$$, 17, 'Outdoor'),
    ($$Red River Gorge$$, 17, 'Outdoor'),
    ($$River Bouldering$$, 17, 'Outdoor'),
    ($$Rock Creek$$, 17, 'Outdoor'),
    ($$Rockcastle River$$, 17, 'Outdoor'),
    ($$Stonecrest$$, 17, 'Outdoor'),
    ($$Caldwell County$$, 17, 'Outdoor'),
    ($$Clifty Hollow$$, 17, 'Outdoor'),
    ($$Hunter Bluff$$, 17, 'Outdoor'),
    ($$Lake morris boulders$$, 17, 'Outdoor'),
    ($$Nolin River Dam$$, 17, 'Outdoor'),
    ($$Pilot Rock$$, 17, 'Outdoor'),
    ($$Shanty Hollow$$, 17, 'Outdoor'),
    ($$Alexandria Climbing Experience$$, 18, 'Gym'),
    ($$Lambright Student Rec. Center$$, 18, 'Gym'),
    ($$LSU Recreation Center$$, 18, 'Gym'),
    ($$New Orleans Boulder Lounge$$, 18, 'Gym'),
    ($$Risen Rock Climbing Gym$$, 18, 'Gym'),
    ($$Slidell Rocks$$, 18, 'Gym'),
    ($$Southern Stone Indoor Climbing$$, 18, 'Gym'),
    ($$Uptown Climbing$$, 18, 'Gym'),
    ($$Alfond Youth Center Rock Wall$$, 19, 'Gym'),
    ($$Antigravity Climbing Wall$$, 19, 'Gym'),
    ($$Bath YMCA$$, 19, 'Gym'),
    ($$Cadillac Mountain Sports / Mt. Desert…$$, 19, 'Gym'),
    ($$Central Lincoln County YMCA$$, 19, 'Gym'),
    ($$EVO Rock + Fitness$$, 19, 'Gym'),
    ($$Gentile Hall Rock Wall$$, 19, 'Gym'),
    ($$Maine Bound$$, 19, 'Gym'),
    ($$North American Outdoor Adventure$$, 19, 'Gym'),
    ($$Penobscot Bay YMCA climbing wall$$, 19, 'Gym'),
    ($$Russel K. Crouse Memorial Climbing Wall$$, 19, 'Gym'),
    ($$Salt Pump Climbing Co.$$, 19, 'Gym'),
    ($$Volta$$, 19, 'Gym'),
    ($$Earth Treks - Hampden$$, 20, 'Gym'),
    ($$Earth Treks Climbing Centers$$, 20, 'Gym'),
    ($$Lifetime Fitness$$, 20, 'Gym'),
    ($$Movement Columbia$$, 20, 'Gym'),
    ($$Movement Rockville$$, 20, 'Gym'),
    ($$Mt. YMCA at the Cumberland YMCA$$, 20, 'Gym'),
    ($$The Boulder Yard$$, 20, 'Gym'),
    ($$The Y of Greater Annapolis$$, 20, 'Gym'),
    ($$YMCA at Stadium Place$$, 20, 'Gym'),
    ($$Aldrich's Club Gymnastic, Inc.$$, 21, 'Gym'),
    ($$Carabiner's Climbing wall$$, 21, 'Gym'),
    ($$Kilpatrick Athletic Center at Bard College at Simon's Rock$$, 21, 'Gym'),
    ($$Willy's World Adventure$$, 21, 'Gym'),
    ($$Berkshire Nautilus$$, 21, 'Gym'),
    ($$Boston Bouldering Project$$, 21, 'Gym'),
    ($$Boston University Fitness and Recreation Center$$, 21, 'Gym'),
    ($$Central Branch YMCA$$, 21, 'Gym'),
    ($$Central Rock - Watertown$$, 21, 'Gym'),
    ($$Central Rock Climbing Gym - Hadley$$, 21, 'Gym'),
    ($$Central Rock Climbing Gym, LLC - Worcester$$, 21, 'Gym'),
    ($$Central Rock Framingham$$, 21, 'Gym'),
    ($$Central Rock Gym - Acton St.$$, 21, 'Gym'),
    ($$Central Rock Gym - Arsenal Yards$$, 21, 'Gym'),
    ($$Central Rock Gym - Boston$$, 21, 'Gym'),
    ($$Central Rock gym - Cambridge$$, 21, 'Gym'),
    ($$Central Rock Gym - Fenway$$, 21, 'Gym'),
    ($$Central Rock Gym - Harvard Square$$, 21, 'Gym'),
    ($$Central Rock Gym - Randolph$$, 21, 'Gym'),
    ($$Central Rock Gym - Stoneham$$, 21, 'Gym'),
    ($$Central Rock Gym - Waltham$$, 21, 'Gym'),
    ($$Dedham Health and Athletic$$, 21, 'Gym'),
    ($$Exxcel Gym$$, 21, 'Gym'),
    ($$Gleason Family YMCA$$, 21, 'Gym'),
    ($$La Vida Rock Gym at Gordon College$$, 21, 'Gym'),
    ($$Latitude Sports Club$$, 21, 'Gym'),
    ($$Lighthouse Fitness$$, 21, 'Gym'),
    ($$Maplewood County Day Camp$$, 21, 'Gym'),
    ($$MetroRock Boston$$, 21, 'Gym'),
    ($$MetroRock Littleton$$, 21, 'Gym'),
    ($$MetroRock Newburyport$$, 21, 'Gym'),
    ($$MIT Climbing Wall$$, 21, 'Gym'),
    ($$Northhampton Athletic Club Rock Wallaby$$, 21, 'Gym'),
    ($$Rock Spot Climbing - Sprague St.$$, 21, 'Gym'),
    ($$Rock Spot Climbing - Old Colony Ave$$, 21, 'Gym'),
    ($$Sterling Gymnastics$$, 21, 'Gym'),
    ($$The El Dojo$$, 21, 'Gym'),
    ($$The YMCA of Greater New Bedford$$, 21, 'Gym'),
    ($$WPI CAVE Bouldering Gym$$, 21, 'Gym'),
    ($$Adventure Seminars at Central Michigan University$$, 22, 'Gym'),
    ($$Alma College Climbing Wall$$, 22, 'Gym'),
    ($$Base Camp Challenge Center$$, 22, 'Gym'),
    ($$Bear creek climbing$$, 22, 'Gym'),
    ($$Calvin university$$, 22, 'Gym'),
    ($$Climb Kalamazoo$$, 22, 'Gym'),
    ($$Climbing Center$$, 22, 'Gym'),
    ($$Downriver Family YMCA$$, 22, 'Gym'),
    ($$DYNO Detroit$$, 22, 'Gym'),
    ($$ELEV8$$, 22, 'Gym'),
    ($$Ferris State University Climbing Wall$$, 22, 'Gym'),
    ($$Ford Community and Performing Arts Center$$, 22, 'Gym'),
    ($$GT-ROCKS$$, 22, 'Gym'),
    ($$Higher Ground$$, 22, 'Gym'),
    ($$Inside Moves$$, 22, 'Gym'),
    ($$Jackson YMCA$$, 22, 'Gym'),
    ($$Life Time Fitness$$, 22, 'Gym'),
    ($$Lifetime Fitness Climbing Wall - Canton$$, 22, 'Gym'),
    ($$Lifetime Fitness Climbing Wall - Shelby$$, 22, 'Gym'),
    ($$Livonia Community Recreation Center$$, 22, 'Gym'),
    ($$MTU Climbing Wall$$, 22, 'Gym'),
    ($$Northern Michigan University Wall$$, 22, 'Gym'),
    ($$Peabody Ice Climbing$$, 22, 'Gym'),
    ($$Planet Rock Climbing Gym and Training Center - Madison Heights$$, 22, 'Gym'),
    ($$Planet Rock Climbing Gym and Training Center - Scio$$, 22, 'Gym'),
    ($$Rochester Hills Lifetime Fitness$$, 22, 'Gym'),
    ($$Scrapyard Climbing Collective$$, 22, 'Gym'),
    ($$Sherman Lake YMCA$$, 22, 'Gym'),
    ($$Terra Firma Bouldering Co.$$, 22, 'Gym'),
    ($$Wayne State University Recreation and Fitness Center$$, 22, 'Gym'),
    ($$Westside Community YMCA$$, 22, 'Gym'),
    ($$WMU Climbing Wall$$, 22, 'Gym'),
    ($$Albert Lea Rock Gym$$, 23, 'Gym'),
    ($$Bemidji State University$$, 23, 'Gym'),
    ($$Climbing Wall - Sports and Health Center$$, 23, 'Gym'),
    ($$Dakotah Sport and Fitness$$, 23, 'Gym'),
    ($$Duluth Climbing and Fitness Cooperative$$, 23, 'Gym'),
    ($$Emma B. Howe YMCA$$, 23, 'Gym'),
    ($$Lake Geneva Christian Center$$, 23, 'Gym'),
    ($$Lifetime Fitness Climbing Wall$$, 23, 'Gym'),
    ($$Midwest Mountaineering$$, 23, 'Gym'),
    ($$Minneapolis Bouldering Project$$, 23, 'Gym'),
    ($$Minnesota Climbing Cooperative$$, 23, 'Gym'),
    ($$Minnesota State University, Mankato Climbing Wall$$, 23, 'Gym'),
    ($$Monticello Community Center$$, 23, 'Gym'),
    ($$Prairie Walls$$, 23, 'Gym'),
    ($$REI Pinnacle$$, 23, 'Gym'),
    ($$Roca Climbing & Fitness$$, 23, 'Gym'),
    ($$Shamineau Adventures$$, 23, 'Gym'),
    ($$Southdale YMCA$$, 23, 'Gym'),
    ($$The A$$, 23, 'Gym'),
    ($$University of Minnesota Center for Outdoor Adventure$$, 23, 'Gym'),
    ($$University of Minnesota RecWell$$, 23, 'Gym'),
    ($$University of Minnesota wall$$, 23, 'Gym'),
    ($$Vertical Endeavors Bloomington$$, 23, 'Gym'),
    ($$Vertical Endeavors Minneapolis$$, 23, 'Gym'),
    ($$Vertical Endeavors St. Paul$$, 23, 'Gym'),
    ($$Vertical Endeavors Twin Cities Bouldering$$, 23, 'Gym'),
    ($$Vertical Endevours Duluth$$, 23, 'Gym'),
    ($$Winona State University Wall (Wabasha Rec Center)$$, 23, 'Gym'),
    ($$Core Cycle & Outdoor$$, 24, 'Gym'),
    ($$Edgewater Mall$$, 24, 'Gym'),
    ($$Joe Frank Sanderson Center MSU$$, 24, 'Gym'),
    ($$Payne Center$$, 24, 'Gym'),
    ($$The Hangout$$, 24, 'Gym'),
    ($$Climb So Ill - St. Louis$$, 25, 'Gym'),
    ($$Climb So Ill - Rivers$$, 25, 'Gym'),
    ($$CoMo Rocks$$, 25, 'Gym'),
    ($$Firley YMCA$$, 25, 'Gym'),
    ($$IBEX Climbing Gym$$, 25, 'Gym'),
    ($$Lifetime Fitness$$, 25, 'Gym'),
    ($$North Kansas City YMCA$$, 25, 'Gym'),
    ($$Rock ON$$, 25, 'Gym'),
    ($$RoKC Climbing Gym$$, 25, 'Gym'),
    ($$ROKC Underground$$, 25, 'Gym'),
    ($$Sequence Climbing$$, 25, 'Gym'),
    ($$St. Louis REI$$, 25, 'Gym'),
    ($$The Bouldering Garden$$, 25, 'Gym'),
    ($$The Center of Clayton$$, 25, 'Gym'),
    ($$University of Missouri$$, 25, 'Gym'),
    ($$Upper Limits -St. Louis$$, 25, 'Gym'),
    ($$Upper Limits - Chesterfield$$, 25, 'Gym'),
    ($$Upper Limits - Maryland Heights$$, 25, 'Gym'),
    ($$Zenith Climbing Center$$, 25, 'Gym'),
    ($$Broadwater Athletic Club$$, 26, 'Gym'),
    ($$Freestone Climbing$$, 26, 'Gym'),
    ($$Helena Climbing Association$$, 26, 'Gym'),
    ($$Hi-Line Climbing Center$$, 26, 'Gym'),
    ($$Kootenai ROCKS Climbing Wall$$, 26, 'Gym'),
    ($$Northern Rockies Outdoors Center$$, 26, 'Gym'),
    ($$Rockfish$$, 26, 'Gym'),
    ($$Spire Climbing Center$$, 26, 'Gym'),
    ($$Steep World$$, 26, 'Gym'),
    ($$Stonetree Climbing Center$$, 26, 'Gym'),
    ($$Summit Climbing Wall$$, 26, 'Gym'),
    ($$University Climbing Wall$$, 26, 'Gym'),
    ($$Approach Climbing Gym$$, 27, 'Gym'),
    ($$Cooper YMCA$$, 27, 'Gym'),
    ($$Fremont Family YMCA$$, 27, 'Gym'),
    ($$Life Time Fitness$$, 27, 'Gym'),
    ($$MW Climbing$$, 27, 'Gym'),
    ($$Scottsbluff YMCA$$, 27, 'Gym'),
    ($$SkateDaze - The Rock$$, 27, 'Gym'),
    ($$University of Nebraska - Omaha$$, 27, 'Gym'),
    ($$University of Nebraska UNL$$, 27, 'Gym'),
    ($$Venture Climb$$, 27, 'Gym'),
    ($$The Refuge Climbing and Fitness$$, 28, 'Gym'),
    ($$BaseCamp at CommRow$$, 28, 'Gym'),
    ($$High Altitude Fitness$$, 28, 'Gym'),
    ($$Mesa Rim Climbing & Fitness$$, 28, 'Gym'),
    ($$Nevada Climbing Centers$$, 28, 'Gym'),
    ($$North Peak$$, 28, 'Gym'),
    ($$Red Rock Climbing Center$$, 28, 'Gym'),
    ($$The Pad Henderson$$, 28, 'Gym'),
    ($$Allard Center YMCA Climbing wall$$, 29, 'Gym'),
    ($$Dartmouth Climbing Gym$$, 29, 'Gym'),
    ($$Indoor Ascent$$, 29, 'Gym'),
    ($$Indoor Climbing Center$$, 29, 'Gym'),
    ($$Keene Family YMCA$$, 29, 'Gym'),
    ($$Liquid Planet Water Park$$, 29, 'Gym'),
    ($$Meredith Community Center$$, 29, 'Gym'),
    ($$NH Climbing & Fitness$$, 29, 'Gym'),
    ($$North Country Climbing Center$$, 29, 'Gym'),
    ($$Proctor Academy$$, 29, 'Gym'),
    ($$The River Valley Club Climbing Wall$$, 29, 'Gym'),
    ($$The White Mountain School$$, 29, 'Gym'),
    ($$Vertical Dreams - Manchester$$, 29, 'Gym'),
    ($$Vertical Dreams - Nashua$$, 29, 'Gym'),
    ($$Workout Club and Wellness Center$$, 29, 'Gym'),
    ($$Elite's Peak at Elite Gymnastics$$, 30, 'Gym'),
    ($$Diamond Rock$$, 30, 'Gym'),
    ($$Elite Climbing, LLC$$, 30, 'Gym'),
    ($$Garden State Rocks$$, 30, 'Gym'),
    ($$Goat Climbing Gym$$, 30, 'Gym'),
    ($$High Exposure$$, 30, 'Gym'),
    ($$Ironwood Outdoor Center$$, 30, 'Gym'),
    ($$Kinetic Climbing NJ$$, 30, 'Gym'),
    ($$Lifetime Athletic Rock Wall$$, 30, 'Gym'),
    ($$Lifetime Fitness$$, 30, 'Gym'),
    ($$Method Climbing$$, 30, 'Gym'),
    ($$Milton and Betty Katz JCC$$, 30, 'Gym'),
    ($$New Jersey Rock Gym$$, 30, 'Gym'),
    ($$Randolph Climbing Center$$, 30, 'Gym'),
    ($$Rockville Climbing Center$$, 30, 'Gym'),
    ($$Rutgers University Rock Gym$$, 30, 'Gym'),
    ($$Somerset Hills YMCA$$, 30, 'Gym'),
    ($$Sports & More$$, 30, 'Gym'),
    ($$Summit YMCA Climbing Wall$$, 30, 'Gym'),
    ($$The Gravity Vault - Brick$$, 30, 'Gym'),
    ($$The Gravity Vault - Chatham$$, 30, 'Gym'),
    ($$The Gravity Vault - Flemington$$, 30, 'Gym'),
    ($$The Gravity Vault - Hoboken$$, 30, 'Gym'),
    ($$The Gravity Vault - Middletown$$, 30, 'Gym'),
    ($$The Gravity Vault - Montclair$$, 30, 'Gym'),
    ($$The Gravity Vault - Upper Saddle River$$, 30, 'Gym'),
    ($$The Gravity Vault Voorhees$$, 30, 'Gym'),
    ($$Up County Bouldering Grotto$$, 30, 'Gym'),
    ($$Up The Wall$$, 30, 'Gym'),
    ($$Clovis Rock Gym$$, 31, 'Gym'),
    ($$Family YMCA, The Wall$$, 31, 'Gym'),
    ($$Kirtland AFB Boulder Lab$$, 31, 'Gym'),
    ($$NMSU Climbing Wall$$, 31, 'Gym'),
    ($$Patriot Outdoors$$, 31, 'Gym'),
    ($$San Juan College Indoor Climbing Facility$$, 31, 'Gym'),
    ($$Santa Fe Climbing Center$$, 31, 'Gym'),
    ($$Stone Age Climbing Gym - Midtown$$, 31, 'Gym'),
    ($$Stone Age Climbing Gym - North$$, 31, 'Gym'),
    ($$The Dungeon$$, 31, 'Gym'),
    ($$B.C's Climbing$$, 32, 'Gym'),
    ($$A.I.R. - Albany& 8217 s Indoor Rock Gym$$, 32, 'Gym'),
    ($$AIR Climbing Facility - Adventures in Reality$$, 32, 'Gym'),
    ($$Angert Family Climbing Wall$$, 32, 'Gym'),
    ($$Aviator Sports and Recreation$$, 32, 'Gym'),
    ($$Brooklyn Bouldering Project$$, 32, 'Gym'),
    ($$Brooklyn Boulders Queensbridge$$, 32, 'Gym'),
    ($$Cayuga Climbs$$, 32, 'Gym'),
    ($$Central Rock Gym - Manhattan$$, 32, 'Gym'),
    ($$Central Rock Gym (Buffalo)$$, 32, 'Gym'),
    ($$Central Rock Gym (Rochester)$$, 32, 'Gym'),
    ($$Central Rock Gym - Chelsea$$, 32, 'Gym'),
    ($$Central Rock Gym - Troy$$, 32, 'Gym'),
    ($$Central Rock Gym Syracuse$$, 32, 'Gym'),
    ($$City Climbers Club (AKA 59th Street Gym)$$, 32, 'Gym'),
    ($$Clark Sports Center$$, 32, 'Gym'),
    ($$Climbing Cave$$, 32, 'Gym'),
    ($$Cornerstone Climbing$$, 32, 'Gym'),
    ($$Crunch$$, 32, 'Gym'),
    ($$GP81$$, 32, 'Gym'),
    ($$Island Rock Gym$$, 32, 'Gym'),
    ($$JCC Family Sports and Fitness$$, 32, 'Gym'),
    ($$Lindseth Climbing Wall$$, 32, 'Gym'),
    ($$Manhattan Plaza Health Club Climbing Wall$$, 32, 'Gym'),
    ($$MetroRock Bushwick$$, 32, 'Gym'),
    ($$Munro Family Climbing Wall$$, 32, 'Gym'),
    ($$New York Health and Raquet Club$$, 32, 'Gym'),
    ($$Niagara Climbing Center$$, 32, 'Gym'),
    ($$Powerplay Recreational Center$$, 32, 'Gym'),
    ($$Rebock Sports Club$$, 32, 'Gym'),
    ($$Red Barn Climbing Gym$$, 32, 'Gym'),
    ($$RockSport$$, 32, 'Gym'),
    ($$Rocventures$$, 32, 'Gym'),
    ($$Steep Rock Bouldering - Lexington Ave.$$, 32, 'Gym'),
    ($$Steep Rock West - Broadway$$, 32, 'Gym'),
    ($$Sunrise Bouldering$$, 32, 'Gym'),
    ($$Table Rock Bouldering$$, 32, 'Gym'),
    ($$The Cliffs at DUMBO$$, 32, 'Gym'),
    ($$The Cliffs at Gowanus$$, 32, 'Gym'),
    ($$The Cliffs at Harlem$$, 32, 'Gym'),
    ($$The Cliffs at Valhalla$$, 32, 'Gym'),
    ($$The Cliffs Long Island City$$, 32, 'Gym'),
    ($$The Crux--Champlain Valley Climbing Center$$, 32, 'Gym'),
    ($$The Edge Halfmoon$$, 32, 'Gym'),
    ($$The Field House Rock Wall$$, 32, 'Gym'),
    ($$The Gravity Vault - Melville$$, 32, 'Gym'),
    ($$The Gravity Vault - Poughkeepsie$$, 32, 'Gym'),
    ($$The Ledge$$, 32, 'Gym'),
    ($$The Rock Club$$, 32, 'Gym'),
    ($$The Rock Health and Fitness$$, 32, 'Gym'),
    ($$The Sports Center Climbing Wall$$, 32, 'Gym'),
    ($$The Sports Club/LA$$, 32, 'Gym'),
    ($$The Wall at Palisades$$, 32, 'Gym'),
    ($$VITAL Climbing Gym - Brooklyn$$, 32, 'Gym'),
    ($$The Edge UNCG's Indoor Climbing Wall$$, 33, 'Gym'),
    ($$UNC Ram's Head Indoor Climbing Wall$$, 33, 'Gym'),
    ($$Appalachian State University Climbing Wall at Student Recreation Center$$, 33, 'Gym'),
    ($$Bigfoot Climbing Gym$$, 33, 'Gym'),
    ($$Brevard Rock Gym$$, 33, 'Gym'),
    ($$Center 45$$, 33, 'Gym'),
    ($$Cliff Hangers Climbing and Fitness$$, 33, 'Gym'),
    ($$Climbmax Climbing at the River$$, 33, 'Gym'),
    ($$ClimbMax Inc.$$, 33, 'Gym'),
    ($$Community Center (Chapel Hill Parks & Rec)$$, 33, 'Gym'),
    ($$Davidson Outdoors Climbing Wall$$, 33, 'Gym'),
    ($$Deadpoint Bouldering and Fitness$$, 33, 'Gym'),
    ($$East Carolina University Rock Wall$$, 33, 'Gym'),
    ($$First Hand Climbing$$, 33, 'Gym'),
    ($$Gnarwall Bouldering Gym$$, 33, 'Gym'),
    ($$Inner Peaks - Matthews$$, 33, 'Gym'),
    ($$Inner Peaks - South End$$, 33, 'Gym'),
    ($$Montford Climbing Wall$$, 33, 'Gym'),
    ($$New Vision Training Center$$, 33, 'Gym'),
    ($$North Carolina State University$$, 33, 'Gym'),
    ($$Progression Climbing Gym$$, 33, 'Gym'),
    ($$Ruby C. Hunt YMCA Climbing Wall$$, 33, 'Gym'),
    ($$Sandhills Vertical Gym$$, 33, 'Gym'),
    ($$The Climbing Place$$, 33, 'Gym'),
    ($$The Riveter$$, 33, 'Gym'),
    ($$The Ultimate Climbing Gym$$, 33, 'Gym'),
    ($$Triangle Rock Club - Durham$$, 33, 'Gym'),
    ($$Triangle Rock Club - Fayetteville$$, 33, 'Gym'),
    ($$Triangle Rock Club - Morrisville$$, 33, 'Gym'),
    ($$Triangle Rock Club - Raleigh$$, 33, 'Gym'),
    ($$U.S. National Whitewater Center$$, 33, 'Gym'),
    ($$UNC Fetzer Indoor Climbing Wall$$, 33, 'Gym'),
    ($$UNCW climbing wall$$, 33, 'Gym'),
    ($$Western Carolina University$$, 33, 'Gym'),
    ($$Wilmington Rock Gym$$, 33, 'Gym'),
    ($$Fargo Climbing$$, 34, 'Gym'),
    ($$Minot Family YMCA Climbing Wall$$, 34, 'Gym'),
    ($$North Dakota State University Wellness Center Climbing Wall$$, 34, 'Gym'),
    ($$Schlossman Family YMCA-West Climbing Wall$$, 34, 'Gym'),
    ($$University of North Dakota Wellness Center Climbing Wall$$, 34, 'Gym'),
    ($$Adventure Center, Indoor Rock Climbing Wall$$, 35, 'Gym'),
    ($$ASCEND Youngstown$$, 35, 'Gym'),
    ($$Beechmont Racquet Club$$, 35, 'Gym'),
    ($$Bloc Garten$$, 35, 'Gym'),
    ($$Blue Ash Recreation Center$$, 35, 'Gym'),
    ($$Bowling Green State University$$, 35, 'Gym'),
    ($$Campus Recreation Center$$, 35, 'Gym'),
    ($$Chambers$$, 35, 'Gym'),
    ($$Chambers Purley Boulders$$, 35, 'Gym'),
    ($$Climb Cincy$$, 35, 'Gym'),
    ($$Climb Cleveland$$, 35, 'Gym'),
    ($$Climb Time - Oakley$$, 35, 'Gym'),
    ($$Climb Time of Blue Ash$$, 35, 'Gym'),
    ($$Climb Toledo$$, 35, 'Gym'),
    ($$Crooksville Recreation Center$$, 35, 'Gym'),
    ($$Hocking College Outdoor Pursuits Climbing Wall$$, 35, 'Gym'),
    ($$Kendall Cliffs$$, 35, 'Gym'),
    ($$Kinetic$$, 35, 'Gym'),
    ($$Lifetime Fitness$$, 35, 'Gym'),
    ($$Lifetime Fitness Climbing Wall$$, 35, 'Gym'),
    ($$Mosaic Climbing$$, 35, 'Gym'),
    ($$Nosotros Downtown$$, 35, 'Gym'),
    ($$Nosotros Rock Climbing Gym$$, 35, 'Gym'),
    ($$Oberlin College Recreation Center$$, 35, 'Gym'),
    ($$On the Rocks Climbing Gym$$, 35, 'Gym'),
    ($$Outdoor Pursuit Center$$, 35, 'Gym'),
    ($$Outdoor Pursuits Climbing Facility$$, 35, 'Gym'),
    ($$Paradiso Climbing Co-Op$$, 35, 'Gym'),
    ($$Ralph J. Stolle Countryside YMCA$$, 35, 'Gym'),
    ($$Rock Mill Climbing Yoga & Fitness$$, 35, 'Gym'),
    ($$Rockquest Climbing Center$$, 35, 'Gym'),
    ($$Shaker Rocks$$, 35, 'Gym'),
    ($$Solutions Gym/Wild Mercantile$$, 35, 'Gym'),
    ($$Student Rec and Wellness Center Climbing Wall$$, 35, 'Gym'),
    ($$Tom W. Davis Climbing Center at Ohio State University$$, 35, 'Gym'),
    ($$University of Dayton Campus Recreation$$, 35, 'Gym'),
    ($$University of Toledo$$, 35, 'Gym'),
    ($$Urban Krag Climbing Center$$, 35, 'Gym'),
    ($$Vandalia Recreation Center$$, 35, 'Gym'),
    ($$Vertical Adventures Rock Climbing$$, 35, 'Gym'),
    ($$Washington Township Recreation Center$$, 35, 'Gym'),
    ($$Westerville Community Center$$, 35, 'Gym'),
    ($$Wright State University$$, 35, 'Gym'),
    ($$Youngstown State University Indoor Rock Climbing Wall$$, 35, 'Gym'),
    ($$Blocworks$$, 36, 'Gym'),
    ($$Climb Tulsa$$, 36, 'Gym'),
    ($$Colvin Center$$, 36, 'Gym'),
    ($$Crag Climb Beavers Bend LLC.$$, 36, 'Gym'),
    ($$Skiatook Central Park$$, 36, 'Gym'),
    ($$Summit - Norman (formerly Climb Up)$$, 36, 'Gym'),
    ($$Summit OKC (Silos)$$, 36, 'Gym'),
    ($$Sun & Ski Sports$$, 36, 'Gym'),
    ($$Threshold Climbing, Fitness and Yoga$$, 36, 'Gym'),
    ($$The Yeti's Lair$$, 37, 'Gym'),
    ($$Bend Rock Gym$$, 37, 'Gym'),
    ($$Brimstone Boulders$$, 37, 'Gym'),
    ($$Climbing Wall - Western Oregon University$$, 37, 'Gym'),
    ($$Club Sport$$, 37, 'Gym'),
    ($$Elevation Bouldering Gym$$, 37, 'Gym'),
    ($$Grants Pass YMCA Climbing Wall$$, 37, 'Gym'),
    ($$Hawthorn Farm Athletic Club$$, 37, 'Gym'),
    ($$Indoor Rock Climbing Center$$, 37, 'Gym'),
    ($$Lincoln City Community Center$$, 37, 'Gym'),
    ($$Movement Portland$$, 37, 'Gym'),
    ($$Mt. Hood Community College Wall$$, 37, 'Gym'),
    ($$Portland Rock Gym$$, 37, 'Gym'),
    ($$Pull Down Climbing$$, 37, 'Gym'),
    ($$Regional Sports Center Climbing Wall$$, 37, 'Gym'),
    ($$Rogue Rock Gym$$, 37, 'Gym'),
    ($$Salem Kroc Center$$, 37, 'Gym'),
    ($$SOU Rock Gym$$, 37, 'Gym'),
    ($$Southwestern Oregon Comm. College Rec Center$$, 37, 'Gym'),
    ($$Stoneworks (Portland)$$, 37, 'Gym'),
    ($$Sunset Athletic Club$$, 37, 'Gym'),
    ($$The Circuit Bouldering Gym - SW Macadam Ave.$$, 37, 'Gym'),
    ($$The Circuit Bouldering Gym - Bend$$, 37, 'Gym'),
    ($$The Circuit Bouldering Gym - NE$$, 37, 'Gym'),
    ($$The Circuit Bouldering Gym - Tigard$$, 37, 'Gym'),
    ($$The Crux Rock Gym$$, 37, 'Gym'),
    ($$The Rock Boxx Climbing Gym$$, 37, 'Gym'),
    ($$The Vault Climbing & Fitness Club$$, 37, 'Gym'),
    ($$University of Oregon Recreation Center Rock Climbing Wall$$, 37, 'Gym'),
    ($$Valley Rock Gym$$, 37, 'Gym'),
    ($$Ozzy's Family Fun Center$$, 38, 'Gym'),
    ($$Abersold Student Recreation Center$$, 38, 'Gym'),
    ($$Ascend Pittsburgh$$, 38, 'Gym'),
    ($$California University of Pennsylvania$$, 38, 'Gym'),
    ($$Camp Fitch YMCA$$, 38, 'Gym'),
    ($$Climb Nittany$$, 38, 'Gym'),
    ($$Climb North$$, 38, 'Gym'),
    ($$Climbnasium$$, 38, 'Gym'),
    ($$Dickinson College$$, 38, 'Gym'),
    ($$Downingtown Rock Gym$$, 38, 'Gym'),
    ($$Doylestown Rock Gym$$, 38, 'Gym'),
    ($$Edinboro University Frank G. Pogue Student Center$$, 38, 'Gym'),
    ($$FA Climbing & Fitness$$, 38, 'Gym'),
    ($$Gravity Vault Radnor$$, 38, 'Gym'),
    ($$Iron City Boulders$$, 38, 'Gym'),
    ($$Jumonville Ben Cromer Adventure Center$$, 38, 'Gym'),
    ($$Juniata Valley YMCA$$, 38, 'Gym'),
    ($$Lititz recROC$$, 38, 'Gym'),
    ($$Middlecreek Area Community Cener (The M.A.C.C.)$$, 38, 'Gym'),
    ($$Milton Rock Gym$$, 38, 'Gym'),
    ($$North Summit Climbing wall$$, 38, 'Gym'),
    ($$NorthStar Adventure at Dutch Springs$$, 38, 'Gym'),
    ($$Paramount Sports Complex$$, 38, 'Gym'),
    ($$Penn State Climbing Wall$$, 38, 'Gym'),
    ($$Philadelphia Rock Gym East Falls$$, 38, 'Gym'),
    ($$Philadelphia Rock Gym Fishtown$$, 38, 'Gym'),
    ($$Philadelphia Rock Gym Malvern$$, 38, 'Gym'),
    ($$Philadelphia Rock Gym Oaks$$, 38, 'Gym'),
    ($$Philadelphia Rock Gym Wyncote$$, 38, 'Gym'),
    ($$Pocono Rocks$$, 38, 'Gym'),
    ($$PRG Valley$$, 38, 'Gym'),
    ($$Reach Rock Climbing Gym and Fitness Center$$, 38, 'Gym'),
    ($$Reading Rocks$$, 38, 'Gym'),
    ($$Refreshing Mountain Camp$$, 38, 'Gym'),
    ($$REI$$, 38, 'Gym'),
    ($$Rock Bottom Climbing$$, 38, 'Gym'),
    ($$Seven Springs Alpine Tower and High R…$$, 38, 'Gym'),
    ($$Spooky Nook Sports - Nook Climbing Gym$$, 38, 'Gym'),
    ($$State College YMCA Rock Climbing Wall$$, 38, 'Gym'),
    ($$The Adventure Center at Skytop Lodge$$, 38, 'Gym'),
    ($$The Big Gray Rock$$, 38, 'Gym'),
    ($$The Cliffs at Callowhill, LLC$$, 38, 'Gym'),
    ($$The Climbing Wall Inc.$$, 38, 'Gym'),
    ($$The Facktory$$, 38, 'Gym'),
    ($$The Goat Fort Indoor Climbing$$, 38, 'Gym'),
    ($$Tufas Boulder Lounge$$, 38, 'Gym'),
    ($$University of Pittsburgh climbing wall$$, 38, 'Gym'),
    ($$Vertical Extreme$$, 38, 'Gym'),
    ($$Vertical Reality Climbing Wall at Dynamats Gymnastics Center$$, 38, 'Gym'),
    ($$Wilkes Barre Rock Climbing Gym Incorporated$$, 38, 'Gym'),
    ($$Central Rock Gym (Warwick)$$, 39, 'Gym'),
    ($$Ocean State Rock Climbing$$, 39, 'Gym'),
    ($$Rock Spot Climbing - Lincoln$$, 39, 'Gym'),
    ($$Rock Spot Climbing - Peace Dale$$, 39, 'Gym'),
    ($$Rock Spot Climbing - Providence$$, 39, 'Gym'),
    ($$Blochaven$$, 40, 'Gym'),
    ($$Climb@Blue Ridge$$, 40, 'Gym'),
    ($$Coastal Climbing$$, 40, 'Gym'),
    ($$Glendale Outdoor Leadership School$$, 40, 'Gym'),
    ($$Goose Creek Community Center Climbing Wall$$, 40, 'Gym'),
    ($$Greenwood Family YMCA$$, 40, 'Gym'),
    ($$projectROCK Easley$$, 40, 'Gym'),
    ($$The Climbing Wall$$, 40, 'Gym'),
    ($$Athletic Club$$, 41, 'Gym'),
    ($$Black Hills Basecamp$$, 41, 'Gym'),
    ($$Climberz$$, 41, 'Gym'),
    ($$Frontier Climbing$$, 41, 'Gym'),
    ($$Rapid City YMCA$$, 41, 'Gym'),
    ($$SDSU Wellness Center$$, 41, 'Gym'),
    ($$USD Wellness Center$$, 41, 'Gym'),
    ($$Austin Peay State University (Foy Fitness Center)$$, 42, 'Gym'),
    ($$Belmont University$$, 42, 'Gym'),
    ($$CHA Activity Center$$, 42, 'Gym'),
    ($$Climb Murfreesboro$$, 42, 'Gym'),
    ($$Climb Nashville - West$$, 42, 'Gym'),
    ($$Climb Nashville East$$, 42, 'Gym'),
    ($$Climbing Wall: East Tennessee State University$$, 42, 'Gym'),
    ($$ClimBRIDGES - BRIDGES Center$$, 42, 'Gym'),
    ($$High Point Climbing and Fitness$$, 42, 'Gym'),
    ($$High Point Climbing and Fitness - Memphis$$, 42, 'Gym'),
    ($$High Point Climbing and Fitness - Riverside$$, 42, 'Gym'),
    ($$Life Time Fitness - Collierville$$, 42, 'Gym'),
    ($$Memphis Rox$$, 42, 'Gym'),
    ($$Middle Tennessee State University$$, 42, 'Gym'),
    ($$Onsight Rock Gym$$, 42, 'Gym'),
    ($$River Sport Climbing Center$$, 42, 'Gym'),
    ($$Synergy Climbing and Ninja$$, 42, 'Gym'),
    ($$Tennessee Technological University$$, 42, 'Gym'),
    ($$The Ascent$$, 42, 'Gym'),
    ($$The Crag at Cool Springs$$, 42, 'Gym'),
    ($$The Crag-South Nashville$$, 42, 'Gym'),
    ($$University of Tennessee$$, 42, 'Gym'),
    ($$University of Tennessee at Chattanooga$$, 42, 'Gym'),
    ($$UT Health Science Center$$, 42, 'Gym'),
    ($$Vanderbilt University$$, 42, 'Gym'),
    ($$St. Mary's University$$, 43, 'Gym'),
    ($$arch$$, 43, 'Gym'),
    ($$Armadillo Boulders$$, 43, 'Gym'),
    ($$Armadillo Boulders - San Marcos$$, 43, 'Gym'),
    ($$Austin Bouldering Project$$, 43, 'Gym'),
    ($$Austin Bouldering Project Westgate$$, 43, 'Gym'),
    ($$Boulders Sport Climbing Center$$, 43, 'Gym'),
    ($$Canyons Rock Climbing$$, 43, 'Gym'),
    ($$Cave Climbing Gym$$, 43, 'Gym'),
    ($$CLIMB Woodlands$$, 43, 'Gym'),
    ($$Corpus Christi All-Star Gym$$, 43, 'Gym'),
    ($$Crux Climbing Center$$, 43, 'Gym'),
    ($$Crux Climbing Center Central$$, 43, 'Gym'),
    ($$Denia Recreation Center Climbing Wall$$, 43, 'Gym'),
    ($$Dyno-Rock$$, 43, 'Gym'),
    ($$Elevator Rock$$, 43, 'Gym'),
    ($$Elzie Odom Athletic Center$$, 43, 'Gym'),
    ($$Inspire Cypress$$, 43, 'Gym'),
    ($$Inspire Spring$$, 43, 'Gym'),
    ($$Jerry D. Morris Recreation Center$$, 43, 'Gym'),
    ($$Life Time Fitness- Lake Houston$$, 43, 'Gym'),
    ($$Main Event Entertainment - Vertical Challenge$$, 43, 'Gym'),
    ($$McLane Student Life Center$$, 43, 'Gym'),
    ($$Momentum - Katy$$, 43, 'Gym'),
    ($$Momentum Silver Street$$, 43, 'Gym'),
    ($$Movement Dallas - The Hill$$, 43, 'Gym'),
    ($$Movement Design District$$, 43, 'Gym'),
    ($$North Austin Rock Gym$$, 43, 'Gym'),
    ($$Oak Point Recreation Center Climbing Wall$$, 43, 'Gym'),
    ($$Oso Climbing Gyms$$, 43, 'Gym'),
    ($$Outdoor Adventure$$, 43, 'Gym'),
    ($$Sam Houston State University Climbing Center$$, 43, 'Gym'),
    ($$Siloville Climbing Gym$$, 43, 'Gym'),
    ($$SMU Climbing Center$$, 43, 'Gym'),
    ($$Space City Rock Climbing Gym$$, 43, 'Gym'),
    ($$Stephen F. Austin Climbing Wall$$, 43, 'Gym'),
    ($$Stone Co. Climbing$$, 43, 'Gym'),
    ($$Stone Moves Indoor Rock Climbing Gym$$, 43, 'Gym'),
    ($$Summit Carrollton$$, 43, 'Gym'),
    ($$Summit Dallas$$, 43, 'Gym'),
    ($$Summit Denton$$, 43, 'Gym'),
    ($$Summit Fort Worth$$, 43, 'Gym'),
    ($$Summit Grapevine 2.0$$, 43, 'Gym'),
    ($$Summit Grapevine Climbing Gym$$, 43, 'Gym'),
    ($$Summit Plano$$, 43, 'Gym'),
    ($$Summit Recreational Center$$, 43, 'Gym'),
    ($$Sun & Ski Sports$$, 43, 'Gym'),
    ($$Texas A&M University Indoor Climbing Facility$$, 43, 'Gym'),
    ($$Texas Rock Gym - Memorial$$, 43, 'Gym'),
    ($$Texas Tech Climbing Center$$, 43, 'Gym'),
    ($$The District$$, 43, 'Gym'),
    ($$The Houstonian$$, 43, 'Gym'),
    ($$The North Texas Outdoor Pursuit Center$$, 43, 'Gym'),
    ($$The Wall Indoor Rock Climbing Boerne Gymnastics Center$$, 43, 'Gym'),
    ($$University of Northern Texas Climbing Wall$$, 43, 'Gym'),
    ($$University of Texas at Dallas University Recreation Climbing Wall$$, 43, 'Gym'),
    ($$University of Texas at San Antonio$$, 43, 'Gym'),
    ($$UTEP Climbing Gym$$, 43, 'Gym'),
    ($$AlpenFit - Indoor Training for Outdoor Life$$, 44, 'Gym'),
    ($$Contact Climbing$$, 44, 'Gym'),
    ($$Dimple Dell$$, 44, 'Gym'),
    ($$Double-Diamond Climbing Wall$$, 44, 'Gym'),
    ($$Elevation Rock Gym$$, 44, 'Gym'),
    ($$Fit Stop Rock Climbing Gym$$, 44, 'Gym'),
    ($$iROCK Utah$$, 44, 'Gym'),
    ($$Lehi Legacy Center$$, 44, 'Gym'),
    ($$Momentum Indoor Climbing Gym$$, 44, 'Gym'),
    ($$Momentum Lehi$$, 44, 'Gym'),
    ($$Momentum Millcreek$$, 44, 'Gym'),
    ($$Salt Lake Bouldering Project$$, 44, 'Gym'),
    ($$SUU Climbing Gym$$, 44, 'Gym'),
    ($$Taylorsville Rec Center$$, 44, 'Gym'),
    ($$Technical Training Center$$, 44, 'Gym'),
    ($$The Front Climbing Club - Ogden$$, 44, 'Gym'),
    ($$The Front Climbing Club - Salt Lake City$$, 44, 'Gym'),
    ($$The Front Climbing Club - South Main$$, 44, 'Gym'),
    ($$The Project$$, 44, 'Gym'),
    ($$The Quarry$$, 44, 'Gym'),
    ($$The Scratch Pad$$, 44, 'Gym'),
    ($$Uintah Recreation Community Center$$, 44, 'Gym'),
    ($$Ultimate Sports Arena$$, 44, 'Gym'),
    ($$Washington City Community Center$$, 44, 'Gym'),
    ($$West Valley Family Fitness Center climbing wall$$, 44, 'Gym'),
    ($$BrattCave$$, 45, 'Gym'),
    ($$Castleton State College Rock Gym$$, 45, 'Gym'),
    ($$Green Mountain Rock Climbing Center$$, 45, 'Gym'),
    ($$Green Mountain Rock Climbing Center - Quechee$$, 45, 'Gym'),
    ($$MetroRock Burlington$$, 45, 'Gym'),
    ($$Motio Rec.$$, 45, 'Gym'),
    ($$Petra Cliffs Climbing Center$$, 45, 'Gym'),
    ($$Valley Rock Gym$$, 45, 'Gym'),
    ($$Crimper's Climbing Gym$$, 46, 'Gym'),
    ($$Burke Gym Climbing Wall$$, 46, 'Gym'),
    ($$Charlotte Fox Climbing Wall at Hollins University$$, 46, 'Gym'),
    ($$Clington Climbing Inc.$$, 46, 'Gym'),
    ($$Corps Physical Training Facility$$, 46, 'Gym'),
    ($$Dulles South Rec Center$$, 46, 'Gym'),
    ($$Eastern Mennonite University$$, 46, 'Gym'),
    ($$Latitude Climbing and Fitness - Virgnia Beach$$, 46, 'Gym'),
    ($$Latitude Climbing and Fitness - Norfolk$$, 46, 'Gym'),
    ($$Lifetime Fitness Climbing Wall - Sully$$, 46, 'Gym'),
    ($$Lifetime Fitness Climbing Wall - Dulles$$, 46, 'Gym'),
    ($$Longwood University Climbing Wall$$, 46, 'Gym'),
    ($$Movement Crystal City$$, 46, 'Gym'),
    ($$Old Dominion University Rockwall$$, 46, 'Gym'),
    ($$Peak Experiences - Richmond$$, 46, 'Gym'),
    ($$Peak Experiences Midlothian$$, 46, 'Gym'),
    ($$Radford University Climbing Wall$$, 46, 'Gym'),
    ($$Rapp Rocks Climbing Gym$$, 46, 'Gym'),
    ($$Recreation Center$$, 46, 'Gym'),
    ($$Rise Up Climbing$$, 46, 'Gym'),
    ($$River Rock Climbing$$, 46, 'Gym'),
    ($$Rocky Top Climbing$$, 46, 'Gym'),
    ($$Send It Climbing$$, 46, 'Gym'),
    ($$Sportrock Climbing - Alexandria$$, 46, 'Gym'),
    ($$Sportrock Climbing - Sterling$$, 46, 'Gym'),
    ($$Sportsplex LFCC Rock Climbing Wall$$, 46, 'Gym'),
    ($$State Climb LLC$$, 46, 'Gym'),
    ($$The College of William & Mary Climbing Wall$$, 46, 'Gym'),
    ($$The Rock Wall$$, 46, 'Gym'),
    ($$Triangle Rock Club - Richmond$$, 46, 'Gym'),
    ($$VCU Cary Street Gym$$, 46, 'Gym'),
    ($$Vertical Rock Climbing and Fitness - Tysons Corner$$, 46, 'Gym'),
    ($$Vertical Rock Climbing Center$$, 46, 'Gym'),
    ($$Virginia Wesleyan College Climbing Wall$$, 46, 'Gym'),
    ($$Wytheville Community Center$$, 46, 'Gym'),
    ($$Bloc Yard Bouldering Gym$$, 47, 'Gym'),
    ($$Burton Adventure Recreation Center$$, 47, 'Gym'),
    ($$Cirque Climbing$$, 47, 'Gym'),
    ($$Climb Tacoma$$, 47, 'Gym'),
    ($$Collective Bouldering Wall$$, 47, 'Gym'),
    ($$Edgeworks Bellevue$$, 47, 'Gym'),
    ($$Edgeworks Climbing wall$$, 47, 'Gym'),
    ($$Edgeworks Seattle$$, 47, 'Gym'),
    ($$EWU Climbing Wall$$, 47, 'Gym'),
    ($$Federal Way Community Center$$, 47, 'Gym'),
    ($$Firstenburg Community Center$$, 47, 'Gym'),
    ($$Half Moon Bouldering$$, 47, 'Gym'),
    ($$High Steppe Climbing Center$$, 47, 'Gym'),
    ($$Indoor Climbing Center$$, 47, 'Gym'),
    ($$Island Rock Gym$$, 47, 'Gym'),
    ($$Jim Parsley Community Center Wall$$, 47, 'Gym'),
    ($$Marymoor Park Outdoor Climbing Wall$$, 47, 'Gym'),
    ($$Momentum Indoor Climbing: SODO$$, 47, 'Gym'),
    ($$North Coast Gymnastics Academy Rock Wall$$, 47, 'Gym'),
    ($$REI - Seattle Flagship Store$$, 47, 'Gym'),
    ($$Riverfront Rock Gym$$, 47, 'Gym'),
    ($$Riverstone Climbing Gym$$, 47, 'Gym'),
    ($$Rock Shop$$, 47, 'Gym'),
    ($$Seattle Bouldering Project$$, 47, 'Gym'),
    ($$Seattle Bouldering Project - Fremont$$, 47, 'Gym'),
    ($$Seattle Bouldering Project Upper Walls$$, 47, 'Gym'),
    ($$Seattle Magnusson Park Wall @ Mountaineers Club House$$, 47, 'Gym'),
    ($$Source Climbing Center$$, 47, 'Gym'),
    ($$South Bellevue Community Center at Eastgate Park$$, 47, 'Gym'),
    ($$Student Recreation Center Rock Climbing Wall$$, 47, 'Gym'),
    ($$Summit Everett$$, 47, 'Gym'),
    ($$The Barn$$, 47, 'Gym'),
    ($$The Centre at Norpoint$$, 47, 'Gym'),
    ($$The ROCK at Tri-City Court Club$$, 47, 'Gym'),
    ($$Uplift Climbing$$, 47, 'Gym'),
    ($$Vertical Club Tacoma$$, 47, 'Gym'),
    ($$Vertical World - Seattle$$, 47, 'Gym'),
    ($$Vertical World - Redmond$$, 47, 'Gym'),
    ($$Vertical World North$$, 47, 'Gym'),
    ($$Vital Climbing Gym$$, 47, 'Gym'),
    ($$Washington State University$$, 47, 'Gym'),
    ($$Whatcom Family YMCA Climbing Wall$$, 47, 'Gym'),
    ($$Wild Walls, Inc.$$, 47, 'Gym'),
    ($$Cairo Outdoors$$, 48, 'Gym'),
    ($$Climbing New Heights$$, 48, 'Gym'),
    ($$Energy Rock Gym$$, 48, 'Gym'),
    ($$GritStone$$, 48, 'Gym'),
    ($$Marshall University Recreation Center$$, 48, 'Gym'),
    ($$Outside In Climbing Gym$$, 48, 'Gym'),
    ($$Passages to Adventure$$, 48, 'Gym'),
    ($$Tucker Boulder Park$$, 48, 'Gym'),
    ($$West Virginia University Student Recreation Center$$, 48, 'Gym'),
    ($$New River Gorge$$, 48, 'Outdoor'),
    ($$Adventure Rock - Walker's Point$$, 49, 'Gym'),
    ($$Milwaukee Turner's Rock Climbing$$, 49, 'Gym'),
    ($$University of Wisconsin-Steven's Point (Health Enhancement Center)$$, 49, 'Gym'),
    ($$Adventure Rock - Brookfield$$, 49, 'Gym'),
    ($$Adventure Rock - Milwaukee$$, 49, 'Gym'),
    ($$Boulders Climbing Gym - Downtown$$, 49, 'Gym'),
    ($$Boulders Climbing Gym - East$$, 49, 'Gym'),
    ($$Carthage College Climbing Wall$$, 49, 'Gym'),
    ($$CLIMB @ the Loop$$, 49, 'Gym'),
    ($$Fond du Lac Climbing Club$$, 49, 'Gym'),
    ($$Grand Geneva Resort & Spa$$, 49, 'Gym'),
    ($$Gravity Trails$$, 49, 'Gym'),
    ($$Greenheck Field House$$, 49, 'Gym'),
    ($$Health Enhancement Center (UW Stevens Point)$$, 49, 'Gym'),
    ($$Iola-Scandinavia Community Fitness &…$$, 49, 'Gym'),
    ($$Kenosha YMCA - Callahan Family Branch$$, 49, 'Gym'),
    ($$Odyssey Climbing + Fitness$$, 49, 'Gym'),
    ($$Summit Strength and Fitness$$, 49, 'Gym'),
    ($$University of Wisconsin-Eau Claire Wall (McPhee Center)$$, 49, 'Gym'),
    ($$University of Wisconsin-La Crosse Wall (Recreational Eagle Center)$$, 49, 'Gym'),
    ($$University of Wisconsin-Oshkosh (Student Rec and Wellness Center)$$, 49, 'Gym'),
    ($$University of Wisconsin-River Falls (Falcon Center)$$, 49, 'Gym'),
    ($$University of Wisconsin-Stout Climbing wall, Stout Adventures$$, 49, 'Gym'),
    ($$University of Wisconsin-Superior (Marcovich Wellness Center)$$, 49, 'Gym'),
    ($$Urban Ecology Center$$, 49, 'Gym'),
    ($$Woodson YMCA Climbing Wall$$, 49, 'Gym'),
    ($$YMCA at Pabst Farms$$, 49, 'Gym'),
    ($$5150 Rock Gym$$, 50, 'Gym'),
    ($$Backyard Bouldering Gym$$, 50, 'Gym'),
    ($$Campbell County Recreation Center$$, 50, 'Gym'),
    ($$Club Energize$$, 50, 'Gym'),
    ($$Elemental Training Center$$, 50, 'Gym'),
    ($$Fall Hall$$, 50, 'Gym'),
    ($$Gottsche Glyphs$$, 50, 'Gym'),
    ($$Pinedale Aquatic Center$$, 50, 'Gym'),
    ($$Source Bouldering Gym$$, 50, 'Gym'),
    ($$The Rock$$, 50, 'Gym');

-- add 3 users, 3 meetups, 3 attendees
-- CREATE TABLE users (
--     id SERIAL PRIMARY KEY,
--     username TEXT UNIQUE NOT NULL,
--     password TEXT NOT NULL,
--     name TEXT,
--     profile_image TEXT,
--     user_age INTEGER,
--     user_gender TEXT,
--     is_parent BOOLEAN,
--     has_dogs BOOLEAN,
--     bio TEXT,
--     location_id INTEGER NOT NULL    
--         REFERENCES locations ON DELETE SET NULL,
--     preferences JSON
-- );

INSERT INTO users (username, 
                    password, 
                    name, 
                    user_age, 
                    user_gender, 
                    is_parent,
                    has_dogs, 
                    bio, 
                    location_id)
VALUES ('testuser1','test','spider man',32,'Male',TRUE,FALSE,'Best climber ever',446),
    ('testuser2','test','wonder woman',46,'Female',FALSE,TRUE,'Trad is rad',446),
    ('testuser3','test','batman',25,'Male',TRUE,FALSE,'Professional urban climber',480);


-- CREATE TABLE meetups (
--     id SERIAL PRIMARY KEY,
--     creator_user_id INTEGER NOT NULL
--         REFERENCES users ON DELETE CASCADE,
--     date DATE NOT NULL,
--     time TIME NOT NULL,
--     duration INTEGER NOT NULL,
--     location_id INT NOT NULL
--         REFERENCES locations ON DELETE SET NULL,
--     description TEXT
-- );

INSERT INTO meetups (creator_user_id,
                    date,
                    time,
                    duration,
                    location_id,
                    description)
VALUES (1,'2023-01-05','10:00 AM',3,480,'Climb and have some beers'),
(2,'2023-01-10','05:00 PM',4,446,'Meetup after work'),
(3,'2023-01-05','08:00 PM',2,446,'Weekly climb session');


-- CREATE TABLE meetups_attendees (
--     meetup_id INTEGER
--         REFERENCES meetups ON DELETE CASCADE,
--     attendee_user_id INTEGER
--         REFERENCES users ON DELETE CASCADE,
--     PRIMARY KEY (meetup_id, attendee_user_id)
-- );

INSERT INTO meetups_attendees (meetup_id, attendee_user_id,join_request_status)
VALUES (1,2,'pending'),
    (1,3,'approved'),
    (2,1,'approved'),
    (3,1,'rejected');